name: build-docker-images

on:
  push:
    branches:
      - 'github_build'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to GitHub Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push nginx image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/images/nginx
          push: true
          tags: docker.pkg.github.com/${{ github.repository_owner }}/build-test/build-test:latest
